spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:h2:mem:jpadb;DB_CLOSE_DELAY=-1;MODE=MYSQL

server:
  servlet:
    context-path: /api/v1

logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR