spring:
  jpa:
    show-sql: true
    # hibernate:
    #   ddl-auto: validate # prod, staging

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:jpadb
    driver-class-name: org.h2.Driver
    username: sa
    password:

# server:
#   servlet:
#     context-path: /api/v1

logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR